available_text_models: ["gpt-4o"]

info:
  gpt-4o:
    type: chat_completion
    name: GPT-4o
    description: GPT-4o - это специальная версия GPT-4, разработанная для оптимальной производительности и точности. Подходит для сложных и детальных задач.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      smart: 5
      fast: 2
      cheap: 2